# coding: utf-8

"""
    Feature Flags API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_evaluate_post_request import V1EvaluatePostRequest

class TestV1EvaluatePostRequest(unittest.TestCase):
    """V1EvaluatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EvaluatePostRequest:
        """Test V1EvaluatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EvaluatePostRequest`
        """
        model = V1EvaluatePostRequest()
        if include_optional:
            return V1EvaluatePostRequest(
                flag_key = 'new-ui',
                env_key = 'prod',
                context = { }
            )
        else:
            return V1EvaluatePostRequest(
        )
        """

    def testV1EvaluatePostRequest(self):
        """Test V1EvaluatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
