# coding: utf-8

"""
    Feature Flags API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v1_config_get(self) -> None:
        """Test case for v1_config_get

        Fetch all flag configs for an environment
        """
        pass

    def test_v1_evaluate_post(self) -> None:
        """Test case for v1_evaluate_post

        Evaluate a feature flag
        """
        pass


if __name__ == '__main__':
    unittest.main()
